name: weather_app
description: Weather app for weather viewing
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  # State management
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3

  # UI
  sliding_up_panel: ^1.0.2
  flutter_slidable: ^0.5.7
  google_fonts: ^1.1.2


  # Data requesting
  dio: ^3.0.10

  # Device permission
  geolocator: ^6.2.1
  connectivity: ^2.0.2

  # Data saving
  shared_preferences: ^0.5.12+4

  # Dart support
  equatable: ^1.2.6
  dartz: ^0.9.2
  get_it: ^5.0.6

  # App logger
  logger: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0

  flutter_launcher_icons: ^0.8.1

  # Translations
  flappy_translator: ^1.5.0



flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"

flappy_translator:
  input_file_path: "lib/core/translations/translations.csv"
  output_dir: "lib/core/translations"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ";"
  start_index: 1
  depend_on_context: false
  use_single_quotes: true
  replace_no_break_spaces: false

flutter:

  uses-material-design: true

  assets:
    - assets/
    # Backgrounds are made by
    # other pretty woman. :)
    # https://vk.com/doom_ed_doomed
    - assets/images/
